spring.application.name=gestion.connaissance
logging.level.root=INFO

springdoc.api-docs.enabled=true
server.servlet.context-path=/api
spring.web.resources.add-mappings=false
spring.elasticsearch.uris=http://localhost:9200/